/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

/**
 *
 * @author Juan Herrera
 */
public class pantallaMundo extends javax.swing.JFrame {


    /**
     * Creates new form pantallaMundo
     */
    public pantallaMundo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personaje = new javax.swing.JLabel();
        muro1 = new javax.swing.JLabel();
        muro2 = new javax.swing.JLabel();
        piso = new javax.swing.JLabel();
        techo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadro.png"))); // NOI18N
        personaje.setToolTipText("");
        getContentPane().add(personaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 50, 40));

        muro1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(muro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 40, 240));

        muro2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(muro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 40, 240));

        piso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(piso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 540, 30));

        techo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(techo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 540, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("UNLOCK CAPITAL LETTERS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 600, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("CONTROLS: W - A - S - D (DESBLOQUEAR MAYUSCULAS)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 600, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
        //Declaro movimiento jugadores//
        //I declare players movement//

        int x = personaje.getX();
        int y = personaje.getY();
        
        //Declaro los muros //
        //I declare the walls//

        int x1 = muro1.getX();
        int x2 = muro2.getX();

        int y2 = muro2.getY();
        int y1 = muro1.getY();
        
        //Declaro el piso//
        //I declare the floors//
        int pisox = piso.getX();
        int pisoy = piso.getY();
        
        //Declaro el techo//
        //I declare the roof//
        int techox = techo.getX();
        int techoy = techo.getY();

       //Condiciones//
       //Conditions//
        if (evt.getKeyChar() == 'd') {
            x = x + 20;
            personaje.setLocation(x, y);

            if (x + personaje.getWidth() >= x2) {
                x = x2 - personaje.getWidth();
                personaje.setLocation(x, y);

            }

        }
        if (evt.getKeyChar() == 'a') {
            x = x - 20;
            personaje.setLocation(x, y);

            if (x - personaje.getWidth() <= x1) {
                x = x1 + personaje.getWidth();
                personaje.setLocation(x, y);

            }

        }

        if (evt.getKeyChar() == 'w') {
            y = y - 20;
            personaje.setLocation(x, y);

            if (y - personaje.getWidth() <= techoy) {
                y = techoy + personaje.getWidth();
                personaje.setLocation(x, y);

            }

        }

        if (evt.getKeyChar() == 's') {
            y = y + 20;
            personaje.setLocation(x, y);

            if (y + personaje.getWidth() >= pisoy) {
                y = pisoy - personaje.getWidth();
                personaje.setLocation(x, y);

            }

        }


    }//GEN-LAST:event_formKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
   
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel muro1;
    private javax.swing.JLabel muro2;
    private javax.swing.JLabel personaje;
    private javax.swing.JLabel piso;
    private javax.swing.JLabel techo;
    // End of variables declaration//GEN-END:variables
}
